# Generated by Django 5.1.5 on 2025-02-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='customer_image/default.jpg', null=True, upload_to='customer_image'),
        ),
    ]
