# Generated by Django 5.1.5 on 2025-02-05 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productattributename_productattributevalue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='productattributename',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productattributename',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='updated_at',
        ),
    ]
