# Generated by Django 5.1.5 on 2025-02-05 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_productattribute_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute_name',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute_value',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='product',
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='product.product')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductAttributeName',
        ),
        migrations.DeleteModel(
            name='ProductAttributeValue',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
