# Generated by Django 5.1.5 on 2025-02-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, default='user_image/default.jpg', null=True, upload_to='user_image'),
        ),
    ]
