# Generated by Django 5.1.5 on 2025-02-23 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_email_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_is_verified',
        ),
    ]
